name: Build & Test & Run experiment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.12"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: cmake .

      - name: Build SPLA
        run: make

      - name: Install pyspla
        run: |
          pip install _deps/spla-src/python
          cp _deps/spla-build/libspla_x64.so /opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/site-packages/pyspla/libspla_x64.so

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run extractor of biggest cc
        working-directory: src
        run: |
          python bfsp_extract_biggest_cc.py --dataset_path ../experiment_graphs/bfsp/graphs/ --selected_graphs facebook_combined musae_facebook_edges

      - name: Run BFS-parents experiment with spla
        working-directory: src
        run: |
          python bfsp_experiment.py --dataset_path ../experiment_graphs/bfsp/biggest_cc/ --count_vertices 3 30 100 --n_repeats 10 --n_trials 5 --random_seed 42 --algo spla --selected_graphs facebook_combined musae_facebook_edges

      - name: Run BFS-parents experiment with graphblas
        working-directory: src
        run: |
          python bfsp_experiment.py --dataset_path ../experiment_graphs/bfsp/biggest_cc/ --count_vertices 3 30 100 --n_repeats 10 --n_trials 5 --random_seed 42 --algo graphblas --selected_graphs facebook_combined musae_facebook_edges

      - name: Run tests
        working-directory: src
        run: |
          pytest

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            **/*.log
            experiment_graphs/bfsp/biggest_cc/*
